# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Review Deno Code"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:
jobs:
  main:
    name: "${{matrix.runon}}"
    permissions:
      contents: "read"
    strategy:
      matrix:
        runon:
          - "ubuntu-latest"
      fail-fast: false
    uses: "hugoalh/hugoalh/.github/workflows/call-review-deno-code-1.yml@main"
    with:
      runon: "${{matrix.runon}}"
